#!/bin/bash
git add .
# read -p "Enter commit message massge: " commitmessage
if [ "$#" -eq 0 ]; then
  message="change commited succefully"
else
  message="$*"
fi
git commit -a -m "$message"
git push origin main