#!/usr/bin/env bash

I=1

while [ $I -lt 101 ]
do
	if [ $((I%3)) == 0 ] && [ $((I % 5)) == 0 ]
	then
		echo "FizzBuzz"
	elif [ $((I%3)) == 0 ]
	then
		echo "Fizz"
	elif [ $((I%5)) == 0 ]
	then
		echo "Buzz"
	else
		echo $I
	fi
I=$(( I+1 ))
done